### ISSUE TITLE
THANK YOU for flashpatcher

### ISSUE THREAD

**Issue by wjl1958** [KuromeSan/FlashPatcher#1]
Thank you, thank you, thank you for FlashPatcher.  It's EXACTLY what I needed to get my HP Printer software to work.

Are you taking donations?

Bill
wlevant@gmail.com

**Comment by KuromeSan** [comment]
Oh, Donations ? Lol I have accepted them a few times in the past- but I don't like to advertise that I do lol

**Comment by KuromeSan** [comment]
thanks.
