### ISSUE TITLE
KB4577586: Update for the removal of Adobe Flash Player on Windows 10

### ISSUE THREAD

**Issue by Bill-Boquet** [KuromeSan/FlashPatcher#10]
First many thanks to KuromeSan for his great FlashPatcher. It allowed me to continue to use a desktop application dependent on Flash after January 12, 2021, namely "HP Solution center" for 10 years old HP Scanjet G2710 Photo Scanner.
https://support.hp.com/us-en/drivers/selfservice/hp-scanjet-g2710-photo-scanner/3423844

However, since installation of Microsoft Update KB4577586 on my computer, the desktop application detects that "the correct version of Adobe Flash Player for Internet Explorer is not installed" and further requests its installation before exiting.

I tried to install "install_flash_player_ppapi.exe" downloaded from the link provided by KuromeSan, applied FlashPatcher, but when opening Internet explorer, there is no additional module "Flash Player" in the list.

I tried to play with the group policies, as explained at the end of the following link :
https://innov8tiv.com/how-to-disable-adobe-flash-in-microsoft-edge-and-internet-explorer-browsers-5/
but have had no luck to reinstall the additional module "Flash Player" in IE, hence no luck to resurrect my desktop application.

I don't have a restoration point before the KB4577586 update date, so am no longer able to disable it. Any clever idea how to circumvent Microsoft "Flash clean-up" ? The alternative is a suboptimal solution or use my other low resolution scanner.

Thanks in advance, best regards, Bill

**Comment by LiEnby** [comment]
just run the Internet Explorer/ActiveX installer in Compatibility Mode for Windows 7. :D

**Comment by Bill-Boquet** [comment]
Thanks for your lightning fast feedback KuromeSan ! In the meantime, I found an interesting thread on the subject :
https://h30434.www3.hp.com/t5/Scanning-Faxing-Copying/HP-Solution-Center-does-not-work/m-p/7986936/highlight/true#M243076

I tested the proposed solution, i.e. uninstall the desktop application + any Flash player leftovers, then reboot. Then first install Flash player from the link you provided, and afterwards reinstall the desktop application. And bingo, it works, even without your FlashPatcher ! Anyhow, I keep all the tools and advices just in case, and experience shows that there are always cases ;-).

Thanks again for your help, best regards, Bill

**Comment by LiEnby** [comment]
right because files loaded locally are uneffected by the killswitch, as was discovered in my inital look into how it worked-
it could also just be that there giving an older verison of the flash player idk

**Comment by Bill-Boquet** [comment]
@KuromeSan : Thanks for your follow-up and your hints. Since then, I tested more thoroughly the issue with my desktop application and read again your comments. I reopen this thread just to let you know what I initially did and understood wrong. You can of course close it after reading, as your solution works perfectly.

The reason why the reinstall of my desktop application worked is simply because a very old version of Adobe Flash Player 10 Active X (10.0.32.18) was installed together. It had nothing to do with the installation of version 32.0.0.465 : as I had installed the wrong PPAPI version, the fact that it worked without your FlashPatcher was simply because the old version (without time bomb) was used instead ! Sorry for being so dumb.

Afterwards, I preferred to anyhow use the latest version 32.0.0.465 you provided. It worked flawlessly with your tips :
- Execute "install_flash_player_ax.exe" **in Compatibility Mode for Windows 7**.
- Just run your FlashPatcher afterwards.

For the ones who would face similar issues with a desktop application, a few additional hints :
- Uninstal your desktop application and all versions of Adobe Flash Player before reinstall.
- Eventually also delete folders "C:\Windows\System32\Macromed" and "C:\Windows\SysWOW64\Macromed"
- I also had to delete the folder "C:\Program Files (x86)\HP\Digital Imaging", otherwise (old) Flash installation was refused.

Finally, I also learned a lot in the detailed explanations of your patch :
https://gist.github.com/KuromeSan/56d8b724c0696b54f9f81994ae3591d1

A big thanks for your work and follow-up 👍. All the best, Bill.
