### ISSUE TITLE
Issue after doing flash patcher

### ISSUE THREAD

**Issue by lAlexl7l** [KuromeSan/FlashPatcher#13]
i have a screensaver taht requires active x i follow the steps but when i install the screensaver and go to the settings i get this error?
https://files.catbox.moe/p8u621.png
Any idea how to fix this?

**Comment by LiEnby** [comment]
maybe it'd be better to use the actural flash.ocx that came with windows 10.. idk

**Comment by LiEnby** [comment]
https://github.com/leecher1337/flashpatch/blob/main/reinst_flash_w10.cmd try using this batch script to install the native windows 10 version instead

**Comment by LiEnby** [comment]
Wait leecher says this has to do with "Infinity" being used as the number it checks against rather than anything else,
i guess it makes sense with the "Floating point error" //

anyway supposadly FlashPatch has a fix for this already. so you could just use there program instead ..

**Comment by lAlexl7l** [comment]
yeah i try his fix and it worked
