### ISSUE TITLE
Add support to remove region restriction.

### ISSUE THREAD

**Issue by eebssk1** [KuromeSan/FlashPatcher#17]
Hi. Could you add support to remove the China region restriction to this tool? I can't access the data the one who create the region patch ,but I have the patched files(ver 32.0).
(His tool is still available(solution is fetched online though) but i can't find a way to contact him for more document.)

**Comment by eebssk1** [comment]
pacthed files here V
https://sh2.godaftwithebk.pub/nextcloud/s/rRfJSNb9kx6RiHp

**Comment by LiEnby** [comment]
This is what CleanFlash does. so maybe just use that instead?
