### ISSUE TITLE
Flash Patcher Problem

### ISSUE THREAD

**Issue by cheriathesummonrr** [KuromeSan/FlashPatcher#3]
Bad news I tried to download The Flash Patcher but it didn't work can you help with that 
send me a email kimhannah979@gmail.com

**Comment by Javadst** [comment]
Is it possible to make a copy that does not show that window and patches it automatically?

**Comment by MetalBrother** [comment]
Yeah, didn't work on my computer neither, probably something was fixed by Adobe

**Comment by KuromeSan** [comment]
Doesnt work how ?

**Comment by LiEnby** [comment]
> Is it possible to make a copy that does not show that window and patches it automatically?
> Thank you.

 i would but like leecher1337 already did... so just use that: https://github.com/leecher1337/flashpatch
