### ISSUE TITLE
Feedback: Does not work on Windows XP SP3

### ISSUE THREAD

**Issue by Myron-S** [KuromeSan/FlashPatcher#4]
The binary as provided does not work on Windows XP SP3 within Hyper-V.

![image](https://user-images.githubusercontent.com/23613424/107152608-ab7ffa00-6960-11eb-8b87-9a43be5e887c.png)

**Comment by KuromeSan** [comment]
Hm it's probably because it uses a bunch of API functions to change permissions to allow it to edit the files on newer versions of Windows. But on XP those permission settings don't even exist.. I can probably make it work on XP though if I explicitly check for it ..

**Comment by Myron-S** [comment]
My reasoning behind this is that, at least, the ActiveX player is used by desktop applications as well as web-based. Windows is depreciating and removing their older browsers.  Edge Legacy is to be permanently removed April update.  Internet Explorer 11 is got it's time coming some time some time after that.

I have an activated Windows XP running within a Hyper-V VM and it will be useful to be able to use Flashplayer based apps safely within the VM.

Also, thank-you for the manual patching information and analysis.  I do wonder if the Chinese used your utility and/or instructions to get their national rail system up-and-running?  :-)

**Comment by KuromeSan** [comment]
It would be funny xD I'm mostly using this to play old flash MMO games but using it to run a huge railroad network sounds fun too

**Comment by Myron-S** [comment]
Seriously.  It happened. 
https://www.thedrive.com/news/38897/adobe-flash-shutdown-halts-chinese-railroad-for-over-16-hours-before-pirated-copy-restores-ops

**Comment by KuromeSan** [comment]
have you got anything to confirm that they used FlashPatcher, or the hex editor method, most places i find say they simply downgraded to an older version of Adobe Flash Player.

**Comment by Myron-S** [comment]
No. That is the only article I've seen. I've not dug deeper into this topic. That article is how I learnt about the kill switch's existence.

**Comment by leecher1337** [comment]
I did a tiny C implementation of the patcher that works fine on Windows XP too, hope it helps: 
https://github.com/leecher1337/flashpatch

**Comment by LiEnby** [comment]
Thanks Leecher! :D
