### ISSUE TITLE
41 engines have detected this file as a Trojan

### ISSUE THREAD

**Issue by Unlimited2018** [KuromeSan/FlashPatcher#6]
Virus Total says it's a Trojan. 41/69 https://www.virustotal.com/gui/file/4f7f28e5fc1aa5a89e942b3f223f6442668510f6051319aaaa9632d94ecee6e4/detection  
Isn't that a lot for a false positive?

**Comment by KuromeSan** [comment]
hm, yeah, there all comming up as "Gen:Variant.MSILHeracles" 

2 possiblities:

1) maybe MSIL Heracles is a file infecting trojan and its on my pc, thus it infects the file whenever i compile it with itself.

2) my code is similar enough to Gen:Variant.MSILHeracles make AV think that it is that-
possibly we use the same code copied off stackoverflow >_<

**Comment by KuromeSan** [comment]
renamed some shit almost all the detections went away- av is weird, lol
i dont understand why but, resolved!

https://www.virustotal.com/gui/file/e42ed7cd4aa13bf2f897046b5217b75f92cfa20e822657c40bdd93840a7485db/detection
